# Header
menu:
  主页: /
  所有文章: /archives
 #随笔: /tags/随笔
  标签: /tags

# SubNav
subnav:
  github: "https://github.com/zhangciba"
  weibo: "http://weibo.com/zhangchixtacbn"
  rss: "#"
  zhihu: "http://www.zhihu.com/people/zhangchixtacbn"
  #douban: "#"
  mail: "zhangchixtacbn@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
baidu_tongji: true
favicon: /favicon.png

#你的头像url
#avatar: http://7xsnoh.com2.z0.glb.clouddn.com/IMG_20160319_163733.jpg
#avatar: http://7xsnoh.com2.z0.glb.clouddn.com/avator.jpg 
avatar: http://7xsnoh.com2.z0.glb.clouddn.com/IMG_0049.JPG
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: true 
#开启——
friends:
  小燕子之家: http://adherence.cn
  豪杰写字的地方: http://blog.jayxhj.com
  大兵奋斗的地方: http://www.cnblogs.com/ryanlamp/
  华中科技大学: http://www.hust.edu.cn

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
#aboutme: 
